import { useState } from 'react'
import { Activity, ArrowDown, ArrowRight, Check, ChevronDown, Cloud, Database, Globe2, Info, Layers3, LockKeyhole, Network, RefreshCw, Route, Server, Shield, ShieldCheck, X } from 'lucide-react'

type NodeData = { id: string; name: string; kind: string; detail: string; color: string; icon: 'internet' | 'route' | 'cloud' | 'alb' | 'ec2' | 'rds' | 'nat' }
const nodeContent: Record<string, Omit<NodeData, 'id' | 'color' | 'icon'>> = {
  internet: { name: 'Internet', kind: 'Entrada de usuarios', detail: 'Los usuarios acceden al dominio público por HTTPS. Route 53 resuelve el nombre y dirige las consultas a la distribución.', },
  route53: { name: 'Amazon Route 53', kind: 'DNS administrado', detail: 'Resuelve northstar.io y dirige el tráfico a CloudFront mediante un registro Alias con comprobaciones de estado.', },
  cloudfront: { name: 'Amazon CloudFront', kind: 'CDN global', detail: 'Entrega contenido desde ubicaciones de borde y comunica el origen con TLS. Puede almacenar contenido estático en caché.', },
  alb: { name: 'Application Load Balancer', kind: 'Balanceo de carga', detail: 'Distribuye solicitudes HTTPS entre destinos EC2 en dos zonas. Los health checks retiran instancias que no responden.', },
  ec2a: { name: 'Amazon EC2 · Zona A', kind: 'Capa de aplicación', detail: 'Instancia del grupo Auto Scaling dentro de una subred pública. El Security Group solo admite tráfico del balanceador.', },
  ec2b: { name: 'Amazon EC2 · Zona B', kind: 'Capa de aplicación', detail: 'Instancia redundante para absorber fallas de una zona. El Auto Scaling Group mantiene la capacidad configurada.', },
  rds: { name: 'Amazon RDS Multi-AZ', kind: 'Base de datos privada', detail: 'Base de datos relacional y réplica síncrona en subredes privadas. Ningún acceso público; solo recibe tráfico de la capa EC2.', },
  nat: { name: 'NAT Gateway', kind: 'Salida controlada', detail: 'Permite que instancias de una subred privada inicien conexiones de salida sin aceptar conexiones iniciadas desde Internet.', },
}
const nodeAppearance: Record<string, { color: string; icon: NodeData['icon'] }> = { internet: { color: 'neutral', icon: 'internet' }, route53: { color: 'orange', icon: 'route' }, cloudfront: { color: 'pink', icon: 'cloud' }, alb: { color: 'blue', icon: 'alb' }, ec2a: { color: 'blue', icon: 'ec2' }, ec2b: { color: 'blue', icon: 'ec2' }, rds: { color: 'violet', icon: 'rds' }, nat: { color: 'amber', icon: 'nat' } }
function Glyph({ kind }: { kind: NodeData['icon'] }) { switch (kind) { case 'internet': return <Globe2 size={19}/>; case 'route': return <Route size={19}/>; case 'cloud': return <Cloud size={19}/>; case 'alb': return <Network size={19}/>; case 'ec2': return <Server size={18}/>; case 'rds': return <Database size={18}/>; case 'nat': return <ArrowRight size={18}/> } }
function ArchitectureNode({ id, selected, onSelect, compact = false }: { id: string; selected: boolean; onSelect: (id: string) => void; compact?: boolean }) { const appearance = nodeAppearance[id]; const content = nodeContent[id]; return <button className={`architecture-node interactive-node ${compact ? 'mini-node' : ''} ${selected ? 'node-selected' : ''}`} onClick={() => onSelect(id)} aria-pressed={selected}><span className={`node-icon node-${appearance.color}`}><Glyph kind={appearance.icon}/></span><b>{content.name}</b><small>{content.kind}</small><span className="node-hint">Ver detalle</span></button> }
function Connector({ label = 'HTTPS' }: { label?: string }) { return <div className="interactive-connector"><span>{label}</span><div><i/><ArrowRight size={15}/></div></div> }

export default function InteractiveNetwork() {
  const [selected, setSelected] = useState('cloudfront')
  const [cdnEnabled, setCdnEnabled] = useState(true)
  const [natEnabled, setNatEnabled] = useState(true)
  const [twoZones, setTwoZones] = useState(true)
  const [flowing, setFlowing] = useState(true)
  const [detailsOpen, setDetailsOpen] = useState(true)
  const current = nodeContent[selected]
  const componentCount = 4 + (cdnEnabled ? 1 : 0) + (twoZones ? 2 : 1) + (twoZones ? 1 : 0) + (natEnabled ? (twoZones ? 2 : 1) : 0)
  return <>
    <div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-dot"/> NETWORK DESIGN <span className="eyebrow-sep">/</span> EXPLORADOR</div><h1>Arquitectura de red</h1><p>Selecciona un componente, configura las capas y sigue el recorrido del tráfico.</p></div><div className="heading-right"><span className="status-tag status-good"><span/> Topología activa</span></div></div>
    <section className="panel topology-workspace"><div className="topology-head"><div><span className="section-overline">DISEÑADOR DE ARQUITECTURA · US-EAST-1</span><h2>Aplicación web multi zona</h2><p>VPC 10.0.0.0/16 <span>·</span> {twoZones ? '2 zonas de disponibilidad' : '1 zona de disponibilidad'} <span>·</span> {componentCount} componentes visibles</p></div><div className="topology-tools"><button className={`btn-outline ${flowing ? 'tool-active' : ''}`} onClick={() => setFlowing(value => !value)}><Activity size={14}/>{flowing ? 'Pausar tráfico' : 'Animar tráfico'}</button><button className="btn-outline" onClick={() => { setSelected('cloudfront'); setCdnEnabled(true); setNatEnabled(true); setTwoZones(true); setFlowing(true) }}><RefreshCw size={14}/> Restablecer</button></div></div>
      <div className={`topology-canvas ${flowing ? 'flowing' : ''}`}>
        <div className="topology-controls"><span className="topology-control-label"><Layers3 size={14}/> Capas visibles</span><label><input type="checkbox" checked={cdnEnabled} onChange={event => { setCdnEnabled(event.target.checked); if (!event.target.checked && selected === 'cloudfront') setSelected('alb') }}/> CloudFront CDN</label><label><input type="checkbox" checked={natEnabled} onChange={event => setNatEnabled(event.target.checked)}/> NAT de salida</label><label><input type="checkbox" checked={twoZones} onChange={event => setTwoZones(event.target.checked)}/> Segunda zona</label><span className="flow-legend"><i/> Tráfico de solicitud</span></div>
        <div className="topology-ingress"><ArchitectureNode id="internet" selected={selected === 'internet'} onSelect={setSelected}/><Connector label="DNS"/><ArchitectureNode id="route53" selected={selected === 'route53'} onSelect={setSelected}/>{cdnEnabled && <><Connector label="HTTPS · TLS"/><ArchitectureNode id="cloudfront" selected={selected === 'cloudfront'} onSelect={setSelected}/></>}<Connector label="443 · ingreso"/></div>
        <div className="vpc-boundary"><div className="vpc-title"><span><Network size={15}/> VPC · 10.0.0.0/16</span><span>2 subredes públicas · {twoZones ? 2 : 1} privadas</span></div><div className="vpc-load-balancer"><ArchitectureNode id="alb" selected={selected === 'alb'} onSelect={setSelected}/><span><ArrowDown size={13}/> Distribuye las solicitudes entre zonas de disponibilidad</span></div><div className="zone-grid">{(twoZones ? ['a', 'b'] : ['a']).map(zone => <div className="zone-column" key={zone}><div className="zone-heading"><span>Availability Zone {zone.toUpperCase()}</span><i className="zone-health"><Check size={11}/> Saludable</i></div><div className="zone-public"><div className="subnet-heading"><Globe2 size={12}/> Subred pública · 10.0.{zone === 'a' ? '0' : '2'}.0/24</div><div className="subnet-center"><ArchitectureNode id={zone === 'a' ? 'ec2a' : 'ec2b'} selected={selected === (zone === 'a' ? 'ec2a' : 'ec2b')} onSelect={setSelected} compact/></div></div>{natEnabled && <div className="nat-row"><div className="nat-label"><ArrowDown size={12}/> Salida a Internet</div><ArchitectureNode id="nat" selected={selected === 'nat'} onSelect={setSelected} compact/></div>}<div className="zone-private"><div className="subnet-heading"><LockKeyhole size={12}/> Subred privada · 10.0.{zone === 'a' ? '1' : '3'}.0/24</div><div className="subnet-center">{zone === 'a' ? <ArchitectureNode id="rds" selected={selected === 'rds'} onSelect={setSelected} compact/> : <div className="replica-node"><Database size={16}/><b>RDS standby</b><small>Réplica Multi-AZ</small></div>}</div></div></div>)}</div><div className="vpc-note"><Shield size={13}/> Security Groups limitan el acceso entre capas · la base de datos no tiene IP pública</div></div>
        <div className="diagram-legend"><span><i className="legend-swatch public-swatch"/> Subred pública</span><span><i className="legend-swatch private-swatch"/> Subred privada</span><span><i className="legend-swatch neutral-swatch"/> Conexión cifrada</span><span className="diagram-region"><Globe2 size={13}/> us-east-1</span></div>
      </div>
      {detailsOpen && <div className="node-detail-drawer"><span className={`drawer-icon node-${nodeAppearance[selected].color}`}><Glyph kind={nodeAppearance[selected].icon}/></span><div className="drawer-copy"><span className="section-overline">DETALLE DEL COMPONENTE · {current.kind}</span><h3>{current.name}</h3><p>{current.detail}</p></div><button className="icon-button" onClick={() => setDetailsOpen(false)} aria-label="Cerrar detalle"><X size={16}/></button></div>}
      {!detailsOpen && <button className="reopen-detail" onClick={() => setDetailsOpen(true)}><Info size={14}/> Mostrar detalle de {current.name}</button>}
    </section>
    <div className="network-interaction-hint"><Info size={15}/><span>Haz clic en cualquier componente del diagrama para consultar su función. Prueba activar y desactivar capas para comparar arquitecturas.</span><ChevronDown size={14}/></div>
    <div className="network-info-grid"><article className="info-card"><span className="network-info-icon blue-soft"><ShieldCheck size={18}/></span><div><b>Defensa en profundidad</b><p>Los Security Groups filtran tráfico por recurso y las Network ACLs agregan control a nivel de subred.</p></div></article><article className="info-card"><span className="network-info-icon green-soft"><Activity size={18}/></span><div><b>Alta disponibilidad</b><p>Al distribuir instancias en varias zonas se mantiene capacidad aunque una zona falle.</p></div></article></div>
  </>
}
