import { useMemo, useState } from 'react'
import { Activity, ArrowRight, Check, ChevronDown, Cloud, Database, Globe2, Network, Search, Server, Shield, X } from 'lucide-react'
import { awsServices, initialDeployments, regions } from '../data/awsServices'
import { useLocalStorageState } from '../hooks/useLocalStorageState'

const iconFor = (name: string) => name.includes('RDS') || name.includes('S3') ? Database : name.includes('VPC') ? Network : name.includes('IAM') ? Shield : name.includes('Cloud') ? Cloud : name.includes('Route') ? Globe2 : name.includes('Watch') ? Activity : Server

export default function InteractiveServices() {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('Todas las categorías')
  const [regionCode, setRegionCode] = useState('us-east-1')
  const [selected, setSelected] = useState<string | null>(null)
  const [deployed, setDeployed] = useLocalStorageState('cloudops-infrastructure', initialDeployments)
  const [planned, setPlanned] = useLocalStorageState<string[]>('cloudops-selected-services', ['Amazon EC2', 'Amazon RDS', 'Amazon S3'])
  const categories = ['Todas las categorías', ...new Set(awsServices.map(service => service.category))]
  const filtered = useMemo(() => awsServices.filter(service => (category === 'Todas las categorías' || service.category === category) && `${service.name} ${service.description} ${service.category}`.toLowerCase().includes(query.toLowerCase())), [category, query])
  const currentRegion = regions.find(region => region.code === regionCode) ?? regions[0]
  const regionResources = deployed[regionCode] ?? []
  const detail = selected ? awsServices.find(service => service.name === selected) : null
  const DetailIcon = detail ? iconFor(detail.name) : Server
  const toggleDeployment = (name: string) => setDeployed(current => ({ ...current, [regionCode]: regionResources.includes(name) ? regionResources.filter(item => item !== name) : [...regionResources, name] }))
  const togglePlan = (name: string) => setPlanned(current => current.includes(name) ? current.filter(item => item !== name) : [...current, name])
  return <>
    <div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-dot"/> AWS SERVICE CATALOG <span className="eyebrow-sep">/</span> EXPLORADOR</div><h1>Servicios AWS</h1><p>Busca, filtra, despliega o incorpora servicios en tu propuesta.</p></div><div className="heading-right"><label className="catalog-region-select"><Globe2 size={14}/><select value={regionCode} onChange={event => setRegionCode(event.target.value)}>{regions.map(region => <option value={region.code} key={region.code}>{region.code}</option>)}</select><ChevronDown size={13}/></label></div></div>
    <div className="catalog-interaction-toolbar"><label className="catalog-search"><Search size={16}/><input placeholder="Busca por servicio, función o categoría..." value={query} onChange={event => setQuery(event.target.value)}/>{query && <button className="clear-query" onClick={() => setQuery('')} aria-label="Limpiar búsqueda"><X size={13}/></button>}</label><label className="catalog-filter"><span>Categoría</span><select value={category} onChange={event => setCategory(event.target.value)}>{categories.map(item => <option key={item}>{item}</option>)}</select><ChevronDown size={14}/></label><span className="catalog-count">{filtered.length} servicios</span></div>
    <div className="catalog-status-strip"><span><i className="live-pulse"/> {regionResources.length} desplegados en <b>{currentRegion.name}</b></span><span><Check size={13}/> {planned.length} en tu propuesta</span><span>Los cambios se guardan en este navegador.</span></div>
    <div className="interactive-catalog-grid">{filtered.map(service => { const ServiceIcon = iconFor(service.name); const isDeployed = regionResources.includes(service.name); const isPlanned = planned.includes(service.name); return <article key={service.name} className={`panel interactive-service-card ${selected === service.name ? 'service-card-selected' : ''}`}><div className="service-card-top"><span className={`service-icon icon-${service.color}`}><ServiceIcon size={19}/></span><span className={`status-tag ${isDeployed ? 'status-good' : 'status-neutral'}`}><span/>{isDeployed ? 'Desplegado' : 'Disponible'}</span><button className="service-details-toggle" onClick={() => setSelected(selected === service.name ? null : service.name)} aria-label={`Ver detalles de ${service.name}`}><ArrowRight size={15}/></button></div><span className="category-chip">{service.category}</span><h2>{service.name}</h2><p>{service.description}</p><div className="service-function"><small>FUNCIÓN PRINCIPAL</small><span>{service.function}</span></div><div className="service-cost-row"><span>{service.monthly === 0 ? 'Sin costo directo' : `Desde ~$${service.monthly}/mes · simulado`}</span><button className={`plan-service-button ${isPlanned ? 'plan-selected' : ''}`} onClick={() => togglePlan(service.name)}>{isPlanned ? <><Check size={12}/> En propuesta</> : 'Añadir al plan'}</button></div><button className={`deployment-action ${isDeployed ? 'remove-deployment' : ''}`} onClick={() => toggleDeployment(service.name)}>{isDeployed ? 'Retirar de esta región' : 'Desplegar en esta región'} <ArrowRight size={13}/></button></article> })}</div>
    {filtered.length === 0 && <div className="empty-state"><Search size={24}/><h3>No encontramos servicios</h3><p>Prueba otra búsqueda o categoría.</p></div>}
    {detail && <div className="service-detail-backdrop" onClick={() => setSelected(null)}><aside className="service-detail-panel" onClick={event => event.stopPropagation()}><div className="detail-panel-heading"><span className={`service-icon icon-${detail.color}`}><DetailIcon size={20}/></span><button className="icon-button" onClick={() => setSelected(null)} aria-label="Cerrar detalle"><X size={17}/></button></div><span className="section-overline">{detail.category} · {regionCode}</span><h2>{detail.name}</h2><p>{detail.description}</p><div className="detail-info-row"><small>FUNCIÓN</small><b>{detail.function}</b></div><div className="detail-info-row"><small>ESTIMACIÓN DIDÁCTICA</small><b>{detail.monthly ? `$${detail.monthly} USD / mes` : 'Sin costo directo estimado'}</b></div><div className="detail-info-row"><small>ESTADO EN {regionCode}</small><b>{regionResources.includes(detail.name) ? 'Desplegado' : 'Aún no desplegado'}</b></div><button className="btn-primary detail-primary" onClick={() => toggleDeployment(detail.name)}>{regionResources.includes(detail.name) ? 'Retirar servicio' : 'Desplegar servicio'} <ArrowRight size={14}/></button><button className="btn-outline detail-secondary" onClick={() => togglePlan(detail.name)}>{planned.includes(detail.name) ? 'Quitar de la propuesta' : 'Añadir a la propuesta'}</button></aside></div>}
  </>
}
