import { useMemo, useState } from 'react'
import { Activity, ArrowRight, Check, ChevronRight, Cloud, Database, Globe2, MapPin, Network, Plus, Server, ShieldCheck, X } from 'lucide-react'
import { awsServices, initialDeployments, regions } from '../data/awsServices'
import { useLocalStorageState } from '../hooks/useLocalStorageState'

const regionDetails: Record<string, { x: number; y: number; area: string }> = {
  'us-east-1': { x: 28.5, y: 31, area: 'NORTH AMERICA' }, 'us-east-2': { x: 27, y: 30, area: 'NORTH AMERICA' },
  'us-west-1': { x: 17, y: 34, area: 'NORTH AMERICA' }, 'us-west-2': { x: 16, y: 32, area: 'NORTH AMERICA' },
  'ca-central-1': { x: 23.1, y: 27, area: 'NORTH AMERICA' }, 'ca-west-1': { x: 18.3, y: 25, area: 'NORTH AMERICA' },
  'mx-central-1': { x: 22.5, y: 43, area: 'NORTH AMERICA' }, 'sa-east-1': { x: 37, y: 70, area: 'SOUTH AMERICA' },
  'eu-west-1': { x: 47.8, y: 25, area: 'EUROPE' }, 'eu-west-2': { x: 50, y: 27, area: 'EUROPE' },
  'eu-west-3': { x: 50.5, y: 29, area: 'EUROPE' }, 'eu-central-1': { x: 52.4, y: 28, area: 'EUROPE' },
  'eu-north-1': { x: 55, y: 20, area: 'EUROPE' }, 'eu-south-1': { x: 52.6, y: 33, area: 'EUROPE' },
  'eu-south-2': { x: 49, y: 33, area: 'EUROPE' }, 'eu-central-2': { x: 53, y: 31, area: 'EUROPE' },
  'af-south-1': { x: 55, y: 83, area: 'AFRICA' }, 'me-south-1': { x: 64, y: 41, area: 'MIDDLE EAST' },
  'me-central-1': { x: 65, y: 43, area: 'MIDDLE EAST' }, 'il-central-1': { x: 59, y: 39, area: 'MIDDLE EAST' },
  'ap-south-1': { x: 70, y: 42, area: 'ASIA PACIFIC' }, 'ap-south-2': { x: 72, y: 45, area: 'ASIA PACIFIC' },
  'ap-east-1': { x: 81.7, y: 38, area: 'ASIA PACIFIC' }, 'ap-east-2': { x: 83.8, y: 39, area: 'ASIA PACIFIC' },
  'ap-northeast-1': { x: 88.6, y: 30, area: 'ASIA PACIFIC' }, 'ap-northeast-2': { x: 85.3, y: 31, area: 'ASIA PACIFIC' },
  'ap-northeast-3': { x: 87.6, y: 33, area: 'ASIA PACIFIC' }, 'ap-southeast-1': { x: 78.8, y: 54, area: 'ASIA PACIFIC' },
  'ap-southeast-2': { x: 92, y: 78, area: 'ASIA PACIFIC' }, 'ap-southeast-3': { x: 79.4, y: 59, area: 'ASIA PACIFIC' },
  'ap-southeast-4': { x: 90.3, y: 81, area: 'ASIA PACIFIC' }, 'ap-southeast-5': { x: 78, y: 52, area: 'ASIA PACIFIC' },
  'ap-southeast-6': { x: 97, y: 86, area: 'ASIA PACIFIC' }, 'ap-southeast-7': { x: 78, y: 49, area: 'ASIA PACIFIC' },
}
const serviceIcon = (name: string) => name.includes('RDS') || name.includes('S3') ? Database : name.includes('VPC') ? Network : name.includes('IAM') ? ShieldCheck : name.includes('Cloud') ? Cloud : Server

export default function InteractiveInfrastructure() {
  const [selectedCode, setSelectedCode] = useState('us-east-1')
  const [deployed, setDeployed] = useLocalStorageState('cloudops-infrastructure', initialDeployments)
  const [selectedService, setSelectedService] = useState<string | null>(null)
  const [filter, setFilter] = useState<'all' | 'active' | 'available'>('all')
  const selected = regions.find(region => region.code === selectedCode) ?? regions[0]
  const resources = deployed[selectedCode] ?? []
  const visibleRegions = useMemo(() => regions.filter(region => filter === 'all' || (filter === 'active' ? (deployed[region.code]?.length ?? 0) > 0 : (deployed[region.code]?.length ?? 0) === 0)), [deployed, filter])
  const toggleService = (name: string) => setDeployed(current => {
    const currentList = current[selectedCode] ?? []
    return { ...current, [selectedCode]: currentList.includes(name) ? currentList.filter(item => item !== name) : [...currentList, name] }
  })
  const detail = selectedService ? awsServices.find(service => service.name === selectedService) : null
  return <>
    <div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-dot"/> AWS GLOBAL INFRASTRUCTURE <span className="eyebrow-sep">/</span> EXPLORADOR</div><h1>Infraestructura global</h1><p>Explora regiones y administra el despliegue de recursos de tu propuesta.</p></div><div className="heading-right"><span className="status-tag status-good"><span/> {Object.values(deployed).filter(items => items.length > 0).length} regiones activas</span></div></div>
    <div className="infra-explorer">
      <section className="panel infra-map-card">
        <div className="infra-map-heading"><div><span className="section-overline">MAPA INTERACTIVO</span><h2>Tu nube alrededor del mundo</h2><p>Selecciona una región en el mapa o en la lista para consultar y editar sus recursos.</p></div><label className="map-filter"><span>Mostrar</span><select value={filter} onChange={event => setFilter(event.target.value as typeof filter)}><option value="all">Todas las regiones</option><option value="active">Con recursos</option><option value="available">Sin recursos</option></select></label></div>
        <div className="interactive-world-map"><div className="map-toolbar"><span><i className="map-dot active-map"/> Región con despliegue</span><span><i className="map-dot empty-map"/> Región disponible</span><span className="map-drag-hint"><MapPin size={12}/> Selecciona un pin</span></div><div className="globe-grid"/><svg className="interactive-continent" viewBox="0 0 900 430" aria-label="Mapa esquemático de las regiones"><defs><linearGradient id="globeShade" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#dbeafe" stopOpacity=".26"/><stop offset="1" stopColor="#60a5fa" stopOpacity=".05"/></linearGradient></defs><path fill="url(#globeShade)" stroke="#94a3b8" strokeOpacity=".26" d="M95 99l58-38 63 7 23 29 55 2 36 44-17 39-43 2-30 45-44 11-33-31-28-66-48-15-19-28zm130 144 47-7 37 45-10 57 24 43-24 53-32-20-6-59-41-48zm212-181 64-27 67 4 48-21 62 22 10 20 53 5 29 34-32 22-72-7-24 27-55 13-29 53-44-6-10-50-40-14-33-35-44-16zm147 169 43-29 54 11 14 42-36 46-4 66-34 45-39-44-15-61 10-37zm158-193 36-15 20 11-15 20-37 8-16-13z"/></svg><svg className="map-links" viewBox="0 0 900 430" aria-hidden="true">{regions.filter(r => (deployed[r.code]?.length ?? 0) > 0 && r.code !== selectedCode).map(region => <line key={region.code} x1={`${regionDetails[selectedCode].x}%`} y1={`${regionDetails[selectedCode].y}%`} x2={`${regionDetails[region.code].x}%`} y2={`${regionDetails[region.code].y}%`}/>)}</svg>{visibleRegions.map(region => { const position = regionDetails[region.code]; const isActive = (deployed[region.code]?.length ?? 0) > 0; return <button key={region.code} className={`infra-pin ${isActive ? 'pin-active' : 'pin-available'} ${selectedCode === region.code ? 'pin-selected' : ''} ${isActive || selectedCode === region.code ? 'pin-show-label' : ''} `} style={{ left: `${position.x}%`, top: `${position.y}%` }} onClick={() => { setSelectedCode(region.code); setSelectedService(null) }} aria-label={`Seleccionar ${region.name}`}><span className="pin-pulse"/><span className="pin-label"><b>{region.code}</b><small>{position.area}</small></span></button> })}</div>
        <div className="infra-map-footer"><span><Activity size={14}/> Latencia estimada desde Lima: <b>{selected.latency}</b></span><span>Vista esquemática · Estimacion referencial, sin medicion en vivo</span></div>
      </section>
      <aside className="infra-region-panel panel"><div className="region-panel-top"><div className="region-panel-icon"><Globe2 size={19}/></div><button className="icon-button" title="Cerrar detalle" onClick={() => setSelectedCode('us-east-1')}><X size={16}/></button></div><span className="section-overline">REGIÓN SELECCIONADA · {selected.code}</span><h2>{selected.name}</h2><p className="selected-region-location"><MapPin size={14}/>{selected.city}</p><div className="region-kpis"><div><b>{resources.length}</b><small>Recursos</small></div><div><b>{selected.latency}</b><small>Latencia simulada desde Lima</small></div><div><b>{resources.length ? 'Activa' : 'Lista'}</b><small>Estado</small></div></div><div className="resource-list-heading"><div><h3>Recursos desplegados</h3><span>{resources.length} servicio{resources.length === 1 ? '' : 's'}</span></div><ChevronRight size={15}/></div><div className="deployed-list">{resources.length ? resources.map(name => { const ServiceIcon = serviceIcon(name); return <button key={name} className={`deployed-resource ${selectedService === name ? 'resource-selected' : ''}`} onClick={() => setSelectedService(selectedService === name ? null : name)}><span className="deployed-icon"><ServiceIcon size={15}/></span><span><b>{name}</b><small>{awsServices.find(item => item.name === name)?.category ?? 'AWS resource'}</small></span><span className="resource-online"><i/>Activo</span></button> }) : <div className="region-empty"><Cloud size={21}/><b>Aún no hay recursos</b><span>Despliega un servicio para incluirlo en tu propuesta.</span></div>}</div><details className="resource-picker"><summary><Plus size={15}/> Añadir o retirar servicios <ChevronRight size={14}/></summary><div>{awsServices.map(service => { const ServiceIcon = serviceIcon(service.name); const isDeployed = resources.includes(service.name); return <button key={service.name} onClick={() => toggleService(service.name)}><span className="deployed-icon"><ServiceIcon size={14}/></span><span>{service.name}</span><span className={`resource-toggle ${isDeployed ? 'toggle-on' : ''}`}>{isDeployed && <Check size={12}/>}</span></button> })}</div></details>{detail && <div className="selected-resource-detail"><span className="section-overline">DETALLE DEL RECURSO</span><b>{detail.name}</b><p>{detail.description}</p><button onClick={() => toggleService(detail.name)}>{resources.includes(detail.name) ? 'Retirar de esta región' : 'Desplegar aquí'} <ArrowRight size={13}/></button></div>}</aside>
    </div>
    <section className="infra-region-list"><div className="infra-list-heading"><div><span className="section-overline">REGIONES AWS</span><h2>Explora tus regiones</h2></div><span>{visibleRegions.length} de {regions.length} regiones</span></div><div className="infra-region-grid">{visibleRegions.map(region => { const isActive = (deployed[region.code]?.length ?? 0) > 0; return <button key={region.code} onClick={() => { setSelectedCode(region.code); setSelectedService(null); document.querySelector('.infra-region-panel')?.scrollIntoView({ behavior: 'smooth', block: 'nearest' }) }} className={`infra-region-tile ${selectedCode === region.code ? 'tile-selected' : ''}`}><span className={`tile-indicator ${isActive ? 'tile-live' : ''}`}/><span><b>{region.name}</b><small>{region.code} · {region.city}</small></span><span className="tile-resources">{deployed[region.code]?.length ?? 0} recursos</span><ArrowRight size={14}/></button> })}</div></section>
    <div className="info-callout"><ShieldCheck size={17}/><p><b>Planifica para resiliencia.</b> Selecciona una región de respaldo y distribuye recursos críticos para mantener la continuidad ante fallas localizadas.</p></div>
  </>
}
